### PR TITLE
Update 11_email-notifications.md

### PR DESCRIPTION
**Pull request by sylee-**

### CODE REVIEW

**Comment by EGypsy** [comment]
👍

**Comment by emfet** [comment]
Looks good, much cleaner

**Review by Haribishop — APPROVED** [review]

**Review by DarklingMuse — APPROVED** [review]
Looking good, nice and clear and straight the point!

**Comment by DarklingMuse** [comment]
New PR for this here: https://github.com/fetlife/help/pull/113

**Pull request closed without merging**
