### PR TITLE
Update 07_can-i-use-a-credit-card-to-support-fetlife.md

### PR DESCRIPTION
**Pull request by DarklingMuse**
@nielsenramon James spotted this - the FAQ still says cc support is not available. I've made a rough first pass at changing this so that it isn't forgotten and is added to our ToDo list!

### CODE REVIEW

**Comment by nielsenramon** [comment]
@DarklingMuse Great catch! I don't think we should be this specific tho. Perhaps just remove the question. WDYT @johnbaku

**Comment by Pairadox** [comment]
@DarklingMuse After some thought, I think @nielsenramon suggestion is better long term.  We added this to our FAQ because we couldn't handle CC.  It's an expected behavior TO allow CC, so the KISS strategy would be just to drop it completely.

**Comment by DarklingMuse** [comment]
@Pairadox @nielsenramon agreed!

**Comment by johnbaku** [comment]
@DarklingMuse great catch, but I agree with the other guys, I think it's best to just remove the question.

**Comment by DarklingMuse** [comment]
@johnbaku @nielsenramon - @nenadjelovac just raised this to me again in PM as he noticed it too  -  I am not sure how to remove an FAQ but I agree we don't need this anymore :)

**Comment by reneklacan** [comment]
@DarklingMuse just removing the file from repository should also remove the question completely ... if not, let me know and we can reindex content

**Comment by DarklingMuse** [comment]
@reneklacan I've removed the file but I can still see the question onsite. Let me know if I removed it from the right place (I delete the file from https://github.com/fetlife/help/tree/master/13_supporting-fetlife)

**Comment by reneklacan** [comment]
@DarklingMuse every change should be performed in pull request, deleting file directly on master branch did not trigger updated, fixed it by manually running update job and now question is gone

**Pull request closed without merging**
