### PR TITLE
Update 10_how-do-i-make-a-secondary-profile.md

### PR DESCRIPTION
**Pull request by sylee-**

### CODE REVIEW

**Comment by emfet** [comment]
Perfect!

**Comment by EGypsy** [comment]
👍

**Review by Haribishop — APPROVED** [review]

**Review by emfet — APPROVED** [review]
👍

**Review by DarklingMuse — APPROVED** [review]
Concise, looks good!

**Comment by DarklingMuse** [comment]
New PR opened for this here: https://github.com/fetlife/help/pull/112

**Pull request closed without merging**
